// Generated: where the game tables and texts live in HOCUS.EXE's data
// segment (registered and shareware v1.1). Do not edit by hand.
#ifndef EXELAYOUT_H
#define EXELAYOUT_H

namespace pocus {

enum ExeTable {
	TBL_JUMP,
	TBL_HIGH_JUMP,
	TBL_DAMAGE,
	TBL_BOSS_X,
	TBL_BOSS_Y,
	TBL_BOSS_FACING,
	TBL_BOSS_THRESHOLD,
	TBL_SPEED,
	TBL_SOUND,
	TBL_SCANCODES,
	TBL_COUNT
};

enum ExePointers {
	PTR_HELP,
	PTR_KEY_NAMES,
	PTR_ACTIONS,
	PTR_MENU_MAIN,
	PTR_MENU_EPISODE,
	PTR_MENU_OPTIONS,
	PTR_MENU_SKILL,
	PTR_MENU_INGAME,
	PTR_MENU_SPEED,
	PTR_COUNT
};

enum ExeString {
	STR_MUSIC_ON,
	STR_MUSIC_OFF,
	STR_SOUND_ON,
	STR_SOUND_OFF,
	STR_GAME_PAUSED,
	STR_QUIT_REMINDER,
	STR_QUIT_QUESTION,
	STR_BONUS_EASY,
	STR_BONUS_MODERATE,
	STR_BONUS_HARD,
	STR_CASTLE_COMPLETE,
	STR_TOUGH_BREAK,
	STR_RESULTS_FOR_LEVEL,
	STR_TREASURES_FOUND,
	STR_TREASURES_AVAILABLE,
	STR_ACCURACY,
	STR_NO_BONUS_ACCURACY,
	STR_CASTLE_NOT_COMPLETE,
	STR_TIME_TO_BEAT,
	STR_YOUR_TIME,
	STR_NO_BONUS_TIME,
	STR_PRESS_ANY_KEY,
	STR_ENTER_NAME,
	STR_IO_ERROR,
	STR_HIGH_SCORES_FOR,
	STR_SELECT_SAVE_SLOT,
	STR_SELECT_RESTORE_SLOT,
	STR_SOUND_FX_VOLUME,
	STR_MUSIC_VOLUME,
	STR_VOLUME_HELP,
	STR_ORDER_LINE_1,
	STR_ORDER_LINE_2,
	STR_KEY_SELECT_TITLE,
	STR_KEY_SELECT_HELP,
	STR_KEY_NEW_TITLE,
	STR_PAGE,
	STR_OF,
	STR_PAGE_NEXT,
	STR_PAGE_PREVIOUS,
	STR_PAGE_BOTH,
	STR_SUB_MENU_HELP,
	STR_COUNT
};

}

#endif // EXELAYOUT_H
